### ISSUE TITLE
online demo please :)?

### ISSUE THREAD

**Issue by winkler1** [felixrieseberg/React-Dropzone#2]
Hi- If it's feasible, would love an online demo of this to add to react.rocks. Thanks!

**Comment by kockok** [comment]
Yes, it would be great if the demo is using Ruby on Rails 4 for backend.

**Comment by felixrieseberg** [comment]
@kockok: If you're wondering about how to use this with Ruby, carrierwave will just work fine. There's [even a small tutorial for using it with Dropzone (and this component is using Dropzone)](http://sudharti.github.io/articles/dropzone-rails/).

**Comment by felixrieseberg** [comment]
@winkler1: I built a small fake online demo, I hope this works for you :) It doesn't actually upload files, but everything else is shown. 

http://reactdropzone.azurewebsites.net/example/

**Comment by winkler1** [comment]
Felix - yes, that's perfect, thanks!

**Comment by kockok** [comment]
As per the demo, it renders 
```
    [Error] SyntaxError: Unexpected use of reserved word 'let' in strict mode
	(anonymous function) (bundle.js, line 21707)
````
